### ISSUE TITLE
Don't you want to call peer_removed here?

### ISSUE THREAD

**Issue by mithrendal** [mikaelho/multipeer#2]
https://github.com/mikaelho/multipeer/blob/de0d913857db8fdfb28306cb05ba7257e1ae755b/multipeer.py#L300

It has certainly no effect on running the demo. But for understanding the code this is maybe a bit misleading...

Or am I wrong???

**Comment by mikaelho** [comment]
Good point, it was a bit of quick midnight coding. Cleaned up in commit ea7b39c.
