### ISSUE TITLE
super class has no parameter initialize_streams

### ISSUE THREAD

**Issue by mithrendal** [mikaelho/multipeer#6]
https://github.com/mikaelho/multipeer/blob/f9a8b5ac5fec63262e651557528b0329b7427c8d/lightcycle.py#L308

Hi @mikaelho maybe you forgot to push your modifications to multipeer.py ?

**Comment by mikaelho** [comment]
Fixed with e40d4237a4f1f688f6239b297d28ccda881320a7

**Comment by mithrendal** [comment]
Game works now. Hey mikaelho the Game looks actually really cool 😎. Nice effects thanks to scripter. Hehe.

Preparing now for deeper analysis...
